version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - loki